### PR TITLE
[FIX] Manage bugs on User Page 

### LINKED ISSUE #39: [FEATURE] Profile page: make dot menu btn for block and report user

### LINKED ISSUE #42: [FIX] User Page: Age not retreived from the backend
Age always showing 24

### PR DESCRIPTION
**Pull request by hosonu**
### Report & Block button
- Added a reusable `KebabMenu` component (⋮ three-dot menu) to unify block/report UI across pages
- Replaced inline Block/Report buttons on the user profile page with the kebab menu
- Refactored ChatBox to use the same shared KebabMenu component
- Block and Report actions now appear in a consistent dropdown menu on both the user profile and chat pages

### Age bugs
- Fixed a bug where every user's age was displayed as 24 on the user profile page due to a hardcoded placeholder value
- Added birthday field to the UserProfile interface to receive the birthdate from the backend API
- Implemented proper age calculation based on the user's actual birthday field

## Related Issue
Closes #39 
Closes #42

### CODE REVIEW

File: frontend/src/app/chat/ChatBox.tsx [hunk 1]
```diff
@@ -170,15 +171,15 @@ const ChatBox = ({ conversationId }: ChatBoxProps) => {
...
-  useEffect(() => {
-    const handleClickOutside = (e: MouseEvent) => {
-      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
-        setMenuOpen(false)
-      }
-    }
-    document.addEventListener('mousedown', handleClickOutside)
-    return () => document.removeEventListener('mousedown', handleClickOutside)
-  }, [])
+  // useEffect(() => {
```
Comment (odkaz) [inline frontend/src/app/chat/ChatBox.tsx]: Can you remove the commented lines?

**Review by odkaz — COMMENTED** [review]
The age issue is still not fixed. Could you take another look?

Image

Image

File: frontend/src/app/chat/ChatBox.tsx (hunk 1 above)
Comment (hosonu) [reply frontend/src/app/chat/ChatBox.tsx]: Clean it, done!

**Comment by hosonu** [comment]
@odkaz 
I completely forgot to push the latest changes🙏

**Review by odkaz — APPROVED** [review]
LGTM!
