### PR TITLE
[FIX] Resolve mandatory eval requirements

### LINKED ISSUE #136: [FIX] Resolve all mandatory eval requirements before defense
## Overview
All fixes will be handled in a single branch: `fix/eval-requirements`.
Each item is cross-referenced against both the subject PDF (v6.1) and the eval sheet.

---

### 🔴 Critical — defense stops or instant fail

- [x] **Seed count below 500**
  `SEED_MORE_USERS=100` produces only ~105 profiles.
  Eval sheet: *"If this crashes or is below 500, mark as crashed and finish evaluation."*
  Fix: change `SEED_MORE_USERS` to `500` in `.env`.

- [x] **No backend guard: like without profile picture**
  PDF v6.1 (IV.5): *"If the current user does not have a profile picture, they cannot perform this action."*
  Eval sheet: *"A user that doesn't have a profile picture can't like another user."*
  `likeService.likeUser()` has no `icon_url` check — API can be bypassed directly.
  Fix: add null check for liker's `icon_url` in `like.service.ts`.

- [x] **MESSAGE notifications never created**
  PDF v6.1 (IV.7): *"When they receive a message"* — notification required.
  Eval sheet: *"The user received a message"* — explicitly listed.
  No `MESSAGE` row is ever inserted into `notifications` table on message send.
  The frontend `NotificationsClient.tsx` already handles `MESSAGE` type but receives nothing.
  Fix: call `notificationService.createNotification()` inside `sendMessage` handler in `chat.handlers.ts`.

---

### 🟡 Partial — likely flagged during evaluation

- [x] **Visit history deduplication**
  PDF v6.1 (IV.5): *"When a user views a profile, it must be recorded in their visit history."*
  Eval sheet: *"there must be a history of visits."*
  Current `UNIQUE (user_id, actor_id, type, reference_id)` constraint silently drops repeated visits from the same user.
  Fix: remove the unique constraint on VIEW type, or use a separate `profile_visits` table.

---

### 🔵 Minor — low risk, quick fix

- [x] **`/settings` missing from middleware matcher**
  All protected routes are in `middleware.ts` except `/settings`.
  Neither PDF nor eval sheet explicitly require this, but it's inconsistent.
  Fix: add `'/settings'` to the matcher array in `frontend/src/middleware.ts`.

---

## Not required (confirmed)

- **IP-based geolocation**: PDF v6.1 explicitly states manual location entry is the
  required fallback (GDPR compliant). Current GPS → manual input → Verify flow satisfies the PDF.
  The eval sheet wording conflicts with the PDF; PDF is authoritative.

---

## Branch
`fix/eval-requirements`

## References
- Subject PDF: `matcha.pdf` v6.1
- Eval sheet: https://www.42evalhub.com/spec/matcha

### PR DESCRIPTION
**Pull request by hosonu**
## Summary

Fixes multiple mandatory requirements identified from the [42 Matcha eval sheet](https://www.42evalhub.com/spec/matcha) and the subject PDF (v6.1) to ensure the project passes defense.

### Changes

- **Reject like without profile picture** — Users without an `icon_url` now receive a 403 when attempting to like. Required by PDF IV.5 and eval sheet.
- **Create MESSAGE notification on chat send** — `sendMessage` handler now inserts a `MESSAGE` notification row and fires a socket event. Required by PDF IV.7 and eval sheet.
- **Refresh VIEW notification on repeat visits** — Changed `ON CONFLICT DO NOTHING` to `DO UPDATE SET created_at = NOW(), is_read = FALSE` so repeat profile visits update the timestamp and re-notify. Required by PDF IV.5 and eval sheet ("history of visits").
- **Add `/settings` to middleware matcher** — Aligns auth protection with all other protected routes.
- **Preserve other user's like on unmatch** — Unlike no longer deletes the reciprocal like; only the initiator's like is removed. Re-liking restores the match instantly.
- **Move match/liked badges to online status line** — Cleaner profile layout; badges now appear next to the online indicator instead of cramped in the `<h1>`.

### Not included (confirmed not required)

- **IP-based geolocation**: PDF v6.1 explicitly requires manual location entry as GDPR-compliant fallback. Current implementation satisfies this.
- **Seed count**: `.env` updated locally (`SEED_MORE_USERS=500`), not tracked in Git. `.env.example` already shows `500`.

## Screen Shot
スクリーンショット 2026-04-07 22 17 59

スクリーンショット 2026-04-07 22 18 45

## Related Issue
Closes #136

### CODE REVIEW

File: backend/src/repositories/notification.repository.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const notificationRepository = {
       INSERT INTO notifications (user_id, actor_id, type, reference_id)
       VALUES ($1, $2, $3, $4)
       ON CONFLICT (user_id, actor_id, type, reference_id)
-      DO NOTHING
+      DO UPDATE SET created_at = NOW(), is_read = FALSE
```
Comment (odkaz) [inline backend/src/repositories/notification.repository.ts]: I don’t think refreshing notifications alone satisfies the visit history requirement, since the spec expects a persistent history of visits.

Also, this implementation would send visit notifications from the same user over and over again, which could lead to spam.

A cleaner approach would be to introduce a profile_visits table to store all visit history, while only sending a notification on the first visit (or using a cooldown).

File: backend/src/services/like.service.ts [hunk 2]
```diff
@@ -13,12 +14,17 @@ export const likeService = {
...
-    const [isBlocked, isBlockedBy, isReported, isReportedBy] = await Promise.all([
+    const [likerRow, isBlocked, isBlockedBy, isReported, isReportedBy] = await Promise.all([
+      pool.query('SELECT icon_url FROM users WHERE id = $1', [likerId]),
       blockRepository.checkBlockExists(likerId, likedId),
       blockRepository.checkBlockExists(likedId, likerId),
       reportRepository.checkReportExists(likerId, likedId),
       reportRepository.checkReportExists(likedId, likerId),
     ]);
+
+    if (!likerRow.rows[0]?.icon_url) {
```
Comment (odkaz) [inline backend/src/services/like.service.ts]: Maybe we should also check the profile itself for consistency with the subject, not just the photossomething like !photos_url && !icon_url

Comment (odkaz) [reply backend/src/services/like.service.ts]: Not directly related to this change, but I noticed a frontend error when loading /profile if icon_url is empty.

You can reproduce this by using a test user with no images.

Might be worth handling this case on the frontend to avoid runtime errors.

File: backend/src/repositories/notification.repository.ts (hunk 1 above)
Comment (hosonu) [reply backend/src/repositories/notification.repository.ts]: "Users must receive real-time notifications for the following events: When their profile has been viewed."

from subjects requirement, I think DO UPDATE is better, but also I implemented profile_visits next commit

File: backend/src/services/like.service.ts (hunk 2 above)
Comment (hosonu) [reply backend/src/services/like.service.ts]: FIxed

File: backend/src/repositories/profile_visit.repository.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+        pv.visitor_id AS id,
+        u.username,
+        u.first_name,
+        u.last_name,
+        u.icon_url,
+        pv.created_at
+      FROM profile_visits pv
+      JOIN users u ON u.id = pv.visitor_id
+      WHERE pv.visited_id = $1
+      ORDER BY pv.visitor_id, pv.created_at DESC
```
Comment (odkaz) [inline backend/src/repositories/profile_visit.repository.ts]: I think this part of the query doesn’t sort by most recent visit globally, but rather by visitor_id due to the ORDER BY pv.visitor_id, pv.created_at DESC used with DISTINCT ON.

While this correctly selects the latest visit per user, the final result isn’t ordered by recency. We’d need an additional ordering step (e.g. wrapping in a subquery and sorting by created_at DESC) to get the expected output.

File: frontend/src/app/profile/page.tsx
Comment (odkaz) [inline frontend/src/app/profile/page.tsx:364]: For the visitors tab, it would be helpful to show the visit timestamp (created_at) alongside the username. That way we keep the identity (@username) while also surfacing when the visit happened, which is more relevant for this view.

File: backend/src/repositories/notification.repository.ts (hunk 1 above)
Comment (odkaz) [reply backend/src/repositories/notification.repository.ts]: @hosonu 
 I think “real-time” here refers to immediate delivery rather than emitting a notification for every single visit. Triggering a notification on each visit (e.g. refreshes) would be quite spammy.

 I suggest we keep the current behavior:

 * notify on the first visit
 * deliver it in real-time via socket
 * track all visits separately in `profile_visits`

 This keeps notifications meaningful while still preserving full visit history.

File: backend/src/repositories/profile_visit.repository.ts (hunk 3 above)
Comment (hosonu) [reply backend/src/repositories/profile_visit.repository.ts]: Fixed

File: frontend/src/app/profile/page.tsx
Comment (hosonu) [reply frontend/src/app/profile/page.tsx:364]: I don't think it's necessary now

File: backend/src/repositories/notification.repository.ts (hunk 1 above)
Comment (hosonu) [reply backend/src/repositories/notification.repository.ts]: Fixed

**Review by odkaz — APPROVED** [review]
LGTM!
