### PR TITLE
[FEATURE] Improve fame rating fix and fix few bugs

### LINKED ISSUE #103: [FIX] Fame rating calculation

### LINKED ISSUE #113: [FEATURE] Notification Unlike user

### LINKED ISSUE #120: [FEATURE] Populate notifications for test users
Populate notifications mock the fame rating

### LINKED ISSUE #122: [FIX] Duplicate match notifications
Duplicate notifications when a user keeps unmatching and matching multiple times

Image

### PR DESCRIPTION
**Pull request by hosonu**
### Overview

This PR reworks the fame rating system and fixes several notification bugs discovered
during the process.

---

#### What is Fame Rating?

Fame rating is a **0–100 score** reflecting how popular a user is relative to everyone
else on the platform. It is used for search filtering and sorting.

#### Old implementation (removed)

Fame rating was computed **on every request** by scanning the entire notifications table
for all users — O(N × notifications) per profile view or search. The formula was also flat
and simplistic:
`LIKE × 5 + VIEW × 1 + MATCH × 10 (capped at 100)`

#### New implementation

Fame rating is now **stored in `users.fame_rating`** and refreshed periodically.
Reads are O(1).

**New scoring formula with time-decay:**

| Signal | < 30 days | 30–90 days | Older |
|---|---|---|---|
| MATCH | +10 | +5 | +2 |
| LIKE (no match) | +7 | +3.5 | +1.4 |
| VIEW | +1 | +0.5 | +0.2 |
| UNLIKE | −3 | −1.5 | −0.6 |
| Being blocked | −5 (flat) | | |
| Being reported | −15 (flat) | | |
| ≥ 2 extra photos | +5 bonus | | |
| ≥ 3 tags | +5 bonus | | |

Raw score is clamped to 0, then `PERCENT_RANK()` converts it to a 0–100 percentile
across all users.

**When is it refreshed?**

| Trigger | Type |
|---|---|
| Server startup | Awaited (blocking) |
| Every hour | Background timer |
| After like / unlike | Fire-and-forget |
| After block | Fire-and-forget |
| After report | Fire-and-forget |

#### Seed data

Added `seedInteractions()` in `seed.ts` to populate the notifications table with
realistic fake VIEWs, LIKEs, MATCHes, and UNLIKEs (with timestamps spread over the
past year) so seeded users start with meaningful, distributed fame ratings instead of
all being 0. Only runs once when the notifications table is empty.

---

### 2. Notification Bug Fixes

These bugs were found while reviewing the notification system as part of the fame rating
work.

#### Bug 1 — UNLIKE notifications accumulated on repeated like/unlike cycles

`UNLIKE` notifications were inserted without a `reference_id` (= `NULL`). In PostgreSQL,
`NULL != NULL` in UNIQUE constraints, so `ON CONFLICT DO NOTHING` never fired. Each
unlike cycle inserted a new row, causing unlimited accumulation in the DB and on screen.

**Fix:** `UNLIKE` now uses `likerId` as `reference_id`, consistent with `LIKE` and `VIEW`.

#### Bug 2 — Re-liking did not clear the UNLIKE notification

After A unlikes B (UNLIKE created), if A likes B again, the UNLIKE notification was
never deleted. B kept a permanent −3 fame penalty even though A came back.

**Fix:** `likeUser` now deletes the stale UNLIKE notification before creating the new LIKE.

#### Bug 3 — Stale LIKE shown alongside MATCH in notification inbox

When A liked B first (B gets a LIKE notification), then B liked A back (match), the old
LIKE was never removed. B's inbox showed both "X liked you" and "You matched with X"
from the same person simultaneously.

**Fix:** `likeUser` now deletes the old LIKE notification when a match is detected.

#### Bug 4 — Block did not clean up UNLIKE notifications

`blockUser` cleaned LIKE, MATCH, and VIEW notifications in both directions, but not
UNLIKE. This caused a double penalty: −3 (UNLIKE) + −5 (block) on the blocked user's
fame rating.

**Fix:** Added UNLIKE cleanup in both directions to `blockUser`.

#### Bug 5 — Frontend did not remove superseded notifications on WebSocket push

When a notification was deleted in the DB (e.g. MATCH deleted on unmatch), the backend
only emitted `unreadNotificationCount` — no signal to remove the specific notification
from the displayed list. Combined with the above bugs, this caused the inbox to show
all historical match/unmatch events stacked.

**Fix:** When a `newNotification` WebSocket event arrives, the frontend now filters out
any existing notification from the same actor that is superseded by the incoming one
before prepending it to the list.

| Incoming | Removes from list |
|---|---|
| `MATCH` | stale `LIKE` or `UNLIKE` from same actor |
| `UNLIKE` | old `MATCH` from same actor |
| `LIKE` | old `UNLIKE` from same actor |

---

## Related Issue
Closes #122
Closes #113 
Closes #120
Closes #103

### CODE REVIEW

File: backend/src/database/seed.ts [hunk 1]
```diff
@@ -333,6 +333,131 @@ export const assignTagsToUser = async (userId: number, tagMap: Map<string, numbe
...
+      await pool.query(
+        `INSERT INTO notifications (user_id, actor_id, type, reference_id, created_at)
+         VALUES ($1, $2, 'VIEW', $3, $4)
+         ON CONFLICT DO NOTHING`,
+        [userId, actorId, actorId, randomDate(0, 365)]
+      )
+    }
+  }
+
+  // --- LIKEs and MATCHes ---
```
Comment (odkaz) [inline backend/src/database/seed.ts:377]: Two concerns about the seed logic:

- It currently inserts directly into notifications without populating the underlying domain state (likes, matches). This makes notifications act as a source of truth, which can lead to inconsistencies and makes debugging harder. Ideally, seed the domain tables first and derive notifications from them.
- Also, random interactions are applied to the 5 loginable users. This makes their state non-deterministic and harder to reason about during testing. It would be better to isolate them from seeded randomness and only generate interactions within the bulk (random) users.

These two changes would make the system more consistent and much easier to debug/validate.

**Comment by hosonu** [comment]
## Fix: Unlike/Unmatch notification and like cleanup

### Bug Fixes

- **Re-match bug after unmatch**: B's like was not removed from the DB on unmatch, causing an immediate re-match on the next like. Fixed by calling `deleteLike(likedId, likerId)` inside the `wasMatch` block.
- **UNLIKE notification on non-match unlike**: "Unmatched you" notification was incorrectly sent even when removing a regular like. Fixed by moving UNLIKE notification creation inside the `wasMatch` block.
- **Stale UNLIKE not cleared on re-like**: Only one direction of UNLIKE notifications was cleared on re-like. Fixed by adding the reverse direction cleanup.

### Feature: Real-time notification removal

When a notification is deleted on the backend, the frontend now receives a `removeNotification` socket event and removes it from the list immediately — no page reload required.

File: backend/src/database/seed.ts (hunk 1 above)
Comment (hosonu) [reply backend/src/database/seed.ts:377]: fixed

**Comment by hosonu** [comment]
Addresses review comments on https://github.com/42-matcha-dev/42-matcha/pull/130#discussion_r3044206324
- Replace notifications-based idempotency guard with likes table check,
  which is the actual domain source of truth
- For one-sided LIKEs: INSERT INTO likes first, then derive LIKE notification
- For MATCHes: INSERT INTO likes (both directions) + conversations first,
  use the real conversation.id as reference_id in MATCH notifications
  instead of the previous synthetic arithmetic id
- Split user insertion loop into fixed test users and faker users;
  pass only faker user IDs to seedInteractions so testuser1–5
  remain in a deterministic, interaction-free state

**Comment by odkaz** [comment]
LGTM!

**Review by odkaz — APPROVED** [review]
